# Generated by Django 4.0.2 on 2022-03-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Non_Veg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Taste', models.CharField(max_length=15)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='restro',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='restro',
            name='Taste',
        ),
    ]
