# Generated by Django 4.0.2 on 2022-03-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_non_veg_remove_restro_price_remove_restro_taste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('Taste', models.CharField(max_length=15)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
