# Generated by Django 4.0.2 on 2022-03-25 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_rename_name_veg_name_rename_price_veg_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restro',
        ),
    ]
