# Generated by Django 4.0.2 on 2022-03-25 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_delete_restro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veg',
            old_name='name',
            new_name='vname',
        ),
        migrations.RenameField(
            model_name='veg',
            old_name='price',
            new_name='vprice',
        ),
        migrations.RenameField(
            model_name='veg',
            old_name='taste',
            new_name='vtaste',
        ),
    ]
