# Generated by Django 4.0.2 on 2022-03-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_rename_name_veg_vname_rename_price_veg_vprice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='non_veg',
            old_name='Name',
            new_name='NV_Name',
        ),
        migrations.RenameField(
            model_name='non_veg',
            old_name='Price',
            new_name='NV_Price',
        ),
        migrations.RenameField(
            model_name='non_veg',
            old_name='Taste',
            new_name='NV_Taste',
        ),
    ]
